name: concurrency-test-2
run-name: ${{github.actor}} is learning github actions
on:
  workflow_dispatch:
concurrency:
  group: sleepy
  cancel-in-progress: false
jobs:
  sleep-job:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: sleep
        run: |
          date
          echo "before sleep"
          sleep 30
          date
          echo "after sleep"
